
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot \
      --webroot-path=/var/www/certbot \
      --email ivanvol9l@gmail.com \
      --agree-tos \
      --no-eff-email \
      -d bsbot.org
